Forms
rachaouldbabaali/blog-app pull request #7
Opened 2023-08-24 15:19 UTC by rachaouldbabaali

In this Pull Request, I have done the following:

- [ ] Created a method called current_user in ApplicationController to make current user data available to all controllers.

- [ ] Created forms to perform the following functions:

1. Create a Post on behalf of the current_user (use the method that you created in your ApplicationController).
2. Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
3. Allow Users to add likes to Posts.

2023-08-24 17:03 UTC, andersonlebon requested changes
## Hi @rachaouldbabaali 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## To highlight :champagne: 
- The routes are well setup :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-24 17:03 UTC, andersonlebon commented on app/controllers/posts_controller.rb
> +  end
- [ ] Currently the post is not created because of a validation error, kindly fix it. the error appears because the comments_counter and the likes_counter are not intialise to 0 when creating a post. you can fix it this way

```suggestion
  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      puts @post.errors.full_messages
      render :new
    end
  end
```

2023-08-24 17:03 UTC, andersonlebon commented on app/views/posts/index.html.erb
> +        <% end %>
- [ ] This is the error I am getting when I try to access the post index page, kindly fix this

![image](https://github.com/rachaouldbabaali/blog-app/assets/65068771/1152e274-ddc0-4c7f-9217-959f1fa19df4)

- [ ] KIndly add also a link to the new post form

2023-08-24 17:03 UTC, andersonlebon commented on app/views/posts/index.html.erb
> +    <%= button_to 'Like Post', user_post_like_path(post.user, post), method: :post,class: "like" %>
- [ ] make sure also the like button works properly 
![image](https://github.com/rachaouldbabaali/blog-app/assets/65068771/c98becae-397c-4e81-9831-521e08b3c508)

2023-08-24 23:44 UTC, DuaneDave approved these changes
Hi @rachaouldbabaali 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Post can be created without errors
✔️ Posts can be liked, awesome 👍 

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 13:53 UTC, rachaouldbabaali commented
Thank you @DuaneDave, I truly appreciate your time and efforts in reviewing my work

2023-08-25 13:53 UTC, merged